services:
  postgres:
    image: postgres:17-alpine
    container_name: rhd_lab3_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/import:ro
      - ./backups:/var/lib/postgresql/backups
    ports:
      - "127.0.0.1:5543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata:
