primary_conninfo = 'host=postgres_master port=5432 user=replicator password=rut_replicator_password application_name=slave1'
primary_slot_name = 'replication_slot_slave1'
hot_standby = on
hot_standby_feedback = on
