server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /back {
        resolver 127.0.0.11 ipv6=off;
        proxy_pass http://back:8080/;
    }
}
