Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false

  config.vm.define "bastion" do |c|
    c.vm.hostname = "bastion"
    c.vm.network "private_network", ip: "192.168.57.10"
    c.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq libnss-mdns ansible curl
    SHELL
  end

  config.vm.define "node1" do |c|
    c.vm.hostname = "node1"
    c.vm.network "private_network", ip: "192.168.57.11"
    c.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq libnss-mdns curl
    SHELL
  end

  config.vm.define "node2" do |c|
    c.vm.hostname = "node2"
    c.vm.network "private_network", ip: "192.168.57.12"
    c.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    c.vm.provision "shell", inline: <<-SHELL
      apt-get update -q
      apt-get install -yq libnss-mdns curl
    SHELL
  end
end
